---
  - name: Install NGINX
    apt:
      name: nginx
      state: present
      update_cache: yes
    tags:
      - nginx
      - nginx-install

  - name: Enable and start NGINX
    service:
      name: nginx
      state: "{{ nginx_service_state }}"
      enabled: "{{ nginx_service_enabled }}"
    tags:
      - nginx
      - nginx-service

  - name: Deploy NGINX configuration
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: '0644'
    notify: Restart NGINX
    tags:
      - nginx
      - nginx-config

  - name: Validate NGINX configuration
    command: nginx -t
    register: nginx_test
    changed_when: false
    failed_when: nginx_test.rc != 0
    notify: Restart NGINX
    tags:
      - nginx
      - nginx-config