---
- name: Install prerequisites for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Remove existing Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
    state: absent
    purge: yes
    autoremove: yes

- name: Install specific Docker version
  apt:
    name:
      - "docker-ce={{ docker_version }}"
      - "docker-ce-cli={{ docker_version }}"
      - containerd.io
    state: present
    update_cache: yes
    dpkg_options: "force-confdef,force-confold"
    allow_downgrade: yes

- name: Add user to docker group
  user:
    name: "{{ system_user }}"
    groups: docker
    append: yes

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Verify Docker installation
  command: docker --version
  register: docker_version_output
  changed_when: false

- name: Display Docker version
  debug:
    msg: "Docker version: {{ docker_version_output.stdout }}"
